# Generated by Django 5.2.4 on 2025-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.category"
            ),
        ),
    ]
